# Generated by Django 4.0.3 on 2022-04-10 23:26

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import extenstion.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('logo', models.ImageField(upload_to=extenstion.utils.get_file_path)),
                ('description', models.TextField()),
                ('start_time', django_jalali.db.models.jDateField()),
                ('finish_time', django_jalali.db.models.jDateField()),
                ('fee', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('START', 'شروع نشده'), ('HOLD', 'در حال برگزاری'), ('FINISHED', 'اتمام یافته')], max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='master.master')),
            ],
        ),
    ]
