# Generated by Django 4.0.3 on 2022-04-16 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_institute'),
        ('institute', '0001_initial'),
        ('course', '0002_course_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='institute.institute'),
        ),
        migrations.AddField(
            model_name='course',
            name='participation',
            field=models.ManyToManyField(to='student.student'),
        ),
    ]
