# Generated by Django 4.0.3 on 2022-04-10 23:26

from django.db import migrations, models
import extenstion.utils
import master.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=125)),
                ('last_name', models.CharField(max_length=125)),
                ('national_code', models.CharField(max_length=125, validators=[master.models.validate_national_code])),
                ('profile_image', models.ImageField(blank=True, upload_to=extenstion.utils.get_file_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
